apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: app_name-deploy
spec: 
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: app_name
    spec:
      containers:
      - name: app_name
        image: busayr/nodejs:app_version
        env:
        - name: PORT
          value: "80"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe: 
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 1
---
kind: Service
apiVersion: v1
metadata:
  name: app_name-svc
spec:
  type: NodePort
  selector:
    app: app_name
  ports: 
  - nodePort: 31001
    protocol: TCP
    port: 80
    targetPort: 80
