apiVersion: extensions/v1beta1
kind: Deployment
metadata: 
  name: demo-app-trigger-deploy
spec: 
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: demo-app-trigger
    spec:
      containers:
      - name: demo-app-trigger
        image: busayr/nodejs:1.0.0
        env:
        - name: PORT
          value: "80"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe: 
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 1
---
kind: Service
apiVersion: v1
metadata:
  name: demo-app-trigger-svc
spec:
  type: NodePort
  selector:
    app: demo-app-trigger
  ports: 
  - nodePort: 
    protocol: TCP
    port: 80
    targetPort: 80